### Assignment 0: Linear Algebra, Probability, and Python Warmup (UNGRADED)

*Goals* The main goal of this assignment is for you to assess whether you have adequate preparation for
the course. It’s fine to not be familiar with every concept here. However, if you find yourself struggling with
much of this assignment, you should ask the course staff whether this course is appropriate for you given
your background. This assignment is designed to take around 2 hours.
This assignment is ungraded! If you wish to discuss any of it, feel free to ask the course staff.

## 1 Linear Algebra
*Q1* For each of the following matrices, give the answer or write “undefined” if the operation is invalid.
You do not need to show work.

In [18]:
import numpy as np

# A
matrix_a = np.array([[1, 2 , 4], [3, 4 , 2]])
matrix_b = np.array([[4], [2]])
print(f"#a shape of A: {matrix_a.shape}, shape of B: {matrix_b.shape}\n Matrix A:\n{matrix_a}\n Matrix B:\n{matrix_b}")
try :
    result = np.matmul(matrix_a, matrix_b)
    print("Result\n", result)
except ValueError as e:
    print("Error:", e)

# B
matrix_a = np.array([[1, 2 , 4], [3, 4 , 2]])
matrix_b = np.array([[4], [5], [2]])
print(f"#b shape of A: {matrix_a.shape}, shape of B: {matrix_b.shape}\n Matrix A:\n{matrix_a}\n Matrix B:\n{matrix_b}")
try :
    result = np.matmul(matrix_a, matrix_b)
    print("Result\n", result)
except ValueError as e:
    print("Error:", e)

# C
matrix_a = np.array([[1, 2 , 4], [3, 4 , 2]])
matrix_b = np.array([[4, 2]])
print("#c shape of A: {}, shape of B: {}\n Matrix A:\n{}\n Matrix B:\n{}".format(matrix_a.shape, matrix_b.shape, matrix_a, matrix_b))
try :
    result = np.matmul(matrix_a, matrix_b)
    print("Result\n", result)
except ValueError as e:
    print("Error:", e)

# D
matrix_a = np.array([[6], [2], [4]]).transpose()
matrix_b = np.array([[5], [2], [1]])
print(f"#d shape of A: {matrix_a.shape}, shape of B: {matrix_b.shape}\n Matrix A:\n{matrix_a}\n Matrix B:\n{matrix_b}")
try :
    result = np.matmul(matrix_a, matrix_b)
    print("Result\n", result)
except ValueError as e:
    print("Error:", e)

#a shape of A: (2, 3), shape of B: (2, 1)
 Matrix A:
[[1 2 4]
 [3 4 2]]
 Matrix B:
[[4]
 [2]]
Error: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)
#b shape of A: (2, 3), shape of B: (3, 1)
 Matrix A:
[[1 2 4]
 [3 4 2]]
 Matrix B:
[[4]
 [5]
 [2]]
Result
 [[22]
 [36]]
#c shape of A: (2, 3), shape of B: (1, 2)
 Matrix A:
[[1 2 4]
 [3 4 2]]
 Matrix B:
[[4 2]]
Error: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)
#d shape of A: (1, 3), shape of B: (3, 1)
 Matrix A:
[[6 2 4]]
 Matrix B:
[[5]
 [2]
 [1]]
Result
 [[38]]


*Q2* Write a matrix operation capturing the following computation. Your answer should be a mathematical
expression involving the vectors/matrices A, B, and C. Your math expression does not need to account for
initialization of A, B, and C; it only needs to return the same value as sum given the same inputs.

In [24]:
A = np.random.rand(3)
B = np.random.rand(3,2)
C = np.random.rand(2)
sum = 0.0
for i in range(0,3):
    for j in range(0,2):
        sum += A[i] * B[i][j] * C[j]
sum

np.float64(0.36381636890776925)

*Q3* Consider the following joint distributions
| P(X,Y) | Y=1 | Y=2 | Y=4 |
|---|---|---|---|
| X=1 | 0.1 | 0.2 | 0.2 |
| X=2 | 0.05 | 0.1 | 0.1 |
| X=3 | 0.1 | 0.1 | 0.05 |

In [29]:
import numpy as np

# Q3 joint distribution table
# Rows = X values (1,2,3), Cols = Y values (1,2,3)
joint_dist = np.array([
    [0.1, 0.2, 0.2],   # X=1
    [0.05, 0.1, 0.1],  # X=2
    [0.1, 0.1, 0.05]   # X=3
])

# Marginals
px = joint_dist.sum(axis=1)  # sum over Y
py = joint_dist.sum(axis=0)  # sum over X

# a) P(X|Y=2)
y2_col = joint_dist[:, 1]
p_y2 = y2_col.sum()
p_x_given_y2 = y2_col / p_y2
print("P(X|Y=2):", p_x_given_y2)

# b) P(Y|X=1)
x1_row = joint_dist[0, :]
p_x1 = x1_row.sum()
p_y_given_x1 = x1_row / p_x1
print("P(Y|X=1):", p_y_given_x1)

# c) Check independence (compare P(X=1)*P(Y=1) with P(X=1,Y=1))
p_x1_y1 = joint_dist[0,0]
ind_check = px[0]*py[0]
print("P(X=1,Y=1) =", p_x1_y1, ", P(X=1)P(Y=1) =", ind_check)

# Q4
# Marginals given
px_q4 = np.array([0.5, 0.5])
py_q4 = np.array([0.2, 0.8])

# a) If independent: P(X=0,Y=0) = P(X=0)P(Y=0)
ind_val = px_q4[0]*py_q4[0]
print("Independent P(X=0,Y=0):", ind_val)

# b) If not independent: bounds
# Lower bound = 0, upper bound = min(P(X=0), P(Y=0))
lower_bound = 0
upper_bound = min(px_q4[0], py_q4[0])
print("Bounds if not independent: [{}, {}]".format(lower_bound, upper_bound))


P(X|Y=2): [0.5  0.25 0.25]
P(Y|X=1): [0.2 0.4 0.4]
P(X=1,Y=1) = 0.1 , P(X=1)P(Y=1) = 0.125
Independent P(X=0,Y=0): 0.1
Bounds if not independent: [0, 0.2]
